id: d71cf90dd0c44250837d3b1d42847c4e
initial_creation_type: ocr
source_metadata:
  volumes:
    c394a182d8894d9cb86d7a468f6fa783:
      base_file: v001.txt
      image_group_id: I1PD95846
      title: ཆོས་ཀྱི་སྐུ་ལ་གནས་པའི་ཡོན་ཏན་ཐུན་མོང་མ་ཡིན་པ་ལ་བསྟོད་པ།
      total_pages: 1539
      volume_number: 1
